# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('siglum', models.CharField(max_length=127)),
                ('country', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('anonymous', models.BooleanField(default=False)),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Composer')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfmark', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('type', models.CharField(max_length=127)),
                ('surface', models.CharField(blank=True, max_length=127, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Archive')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Source'),
        ),
    ]
