# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160503_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Archive'),
        ),
    ]
